USE [master]
GO

/****** Object:  Database [medicalrecordsample]    Script Date: 4/26/2021 12:27:22 PM ******/
CREATE DATABASE [medicalrecordsample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'medicalrecordsample', FILENAME = N'D:\SQL\MSSQL15.SQLEXPRESS\MSSQL\DATA\medicalrecordsample.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'medicalrecordsample_log', FILENAME = N'D:\SQL\MSSQL15.SQLEXPRESS\MSSQL\DATA\medicalrecordsample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [medicalrecordsample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [medicalrecordsample] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [medicalrecordsample] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [medicalrecordsample] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [medicalrecordsample] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [medicalrecordsample] SET ARITHABORT OFF 
GO

ALTER DATABASE [medicalrecordsample] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [medicalrecordsample] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [medicalrecordsample] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [medicalrecordsample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [medicalrecordsample] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [medicalrecordsample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [medicalrecordsample] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [medicalrecordsample] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [medicalrecordsample] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [medicalrecordsample] SET  ENABLE_BROKER 
GO

ALTER DATABASE [medicalrecordsample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [medicalrecordsample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [medicalrecordsample] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [medicalrecordsample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [medicalrecordsample] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [medicalrecordsample] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [medicalrecordsample] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [medicalrecordsample] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [medicalrecordsample] SET  MULTI_USER 
GO

ALTER DATABASE [medicalrecordsample] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [medicalrecordsample] SET DB_CHAINING OFF 
GO

ALTER DATABASE [medicalrecordsample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [medicalrecordsample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [medicalrecordsample] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [medicalrecordsample] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [medicalrecordsample] SET QUERY_STORE = OFF
GO

ALTER DATABASE [medicalrecordsample] SET  READ_WRITE 
GO


